/**
 * The trap, the band, and the object that comes out.
 *
 * No network: every mesh here is either the checked-in 5,984-byte catalog mesh or
 * generated by `fixtures/stl.ts`.
 *
 * The first block is the row's reason for existing. `weld()` then `simplify()` is
 * the standard recipe and it no-ops silently on STL geometry, so these tests are
 * written to **fail if the assertion is deleted** rather than merely to describe
 * it — `decimate` and `weldPositions` both refuse a mesh that did not weld, and
 * two tests here call them with one.
 */
import { describe, expect, it } from 'vitest'

import { Document } from '@gltf-transform/core'
import { VertexCountMethod, getSceneVertexCount, weld } from '@gltf-transform/functions'

import { parseStl } from '../../src/three/stl/parse'

import {
  COPYRIGHT,
  EmptyMeshError,
  TOOL,
  TargetMissedError,
  WELD_MIN_DROP,
  WeldNoOpError,
  assertWeldDropped,
  buildDocument,
  decimate,
  readGlb,
  weldPositions,
} from './decimate'
import { MAX_TRIANGLES, MIN_TRIANGLES } from './mesh'
import { asciiStl, binaryStl, box, disconnectedSoup, facetNormals, icosphere } from './fixtures/stl'
import { FIXTURE_TRIANGLES, FIXTURE_WELD, fixtureStl } from './fixtures/wall'

/** A binary STL of `20 × 4^n` triangles with real per-facet normals. */
function sphereStl(subdivisions: number): Uint8Array {
  return binaryStl(icosphere(subdivisions))
}

/** Vertex counts either side of `weld()` for a document built by `build`. */
async function weldCounts(build: () => Document): Promise<{ before: number; after: number }> {
  const doc = build()
  const scene = doc.getRoot().listScenes()[0]
  if (scene === undefined) throw new Error('no scene')
  const before = getSceneVertexCount(scene, VertexCountMethod.UPLOAD)
  await doc.transform(weld())
  return { before, after: getSceneVertexCount(scene, VertexCountMethod.UPLOAD) }
}

describe('the weld trap', () => {
  it('does not merge anything when facet normals survive into weld()', async () => {
    const stl = sphereStl(3)
    const parsed = parseStl(stl)
    const normals = facetNormals(stl)

    const counts = await weldCounts(() => {
      const doc = new Document()
      const buffer = doc.createBuffer()
      const prim = doc
        .createPrimitive()
        .setAttribute('POSITION', doc.createAccessor().setType('VEC3').setArray(new Float32Array(parsed.positions)).setBuffer(buffer))
        // The naive conversion. This is the whole bug.
        .setAttribute('NORMAL', doc.createAccessor().setType('VEC3').setArray(normals).setBuffer(buffer))
      doc.createScene().addChild(doc.createNode().setMesh(doc.createMesh().addPrimitive(prim)))
      return doc
    })

    expect(counts.before).toBe(parsed.triangles * 3)
    // Nothing worth calling a reduction, and no error from weld() itself.
    expect(counts.after / counts.before).toBeGreaterThan(WELD_MIN_DROP)
    expect(() => {
      assertWeldDropped(counts.before, counts.after, WELD_MIN_DROP, parsed.triangles)
    }).toThrow(WeldNoOpError)
  })

  it('merges to about a sixth once the facet normals are dropped', async () => {
    const parsed = parseStl(sphereStl(3))
    const counts = await weldCounts(() => buildDocument(new Float32Array(parsed.positions), null))

    expect(counts.before).toBe(parsed.triangles * 3)
    expect(counts.after / counts.before).toBeLessThan(0.18)
    expect(() => {
      assertWeldDropped(counts.before, counts.after, WELD_MIN_DROP, parsed.triangles)
    }).not.toThrow()
  })

  it('reproduces the ratio on a real catalog mesh', async () => {
    const parsed = parseStl(fixtureStl())
    expect(parsed.triangles).toBe(FIXTURE_TRIANGLES)

    const welded = await weldPositions(parsed.positions)
    expect(welded.report.before).toBe(FIXTURE_WELD.before)
    expect(welded.report.after).toBe(FIXTURE_WELD.after)
    expect(welded.report.ratio).toBeCloseTo(0.1667, 3)
  })

  it('refuses a mesh that did not weld — deleting the guard fails this test', async () => {
    // 40 disconnected triangles: 120 unshared corners, nothing to merge, and
    // nothing simplification could collapse either.
    await expect(weldPositions(disconnectedSoup(40))).rejects.toThrow(WeldNoOpError)
  })

  it('refuses it through decimate() too, so no caller can route around the guard', async () => {
    await expect(decimate(binaryStl(disconnectedSoup(40)))).rejects.toThrow(WeldNoOpError)
  })

  it('skips the ratio check below a cube, where it would mean nothing', () => {
    // One triangle welds 3 -> 3 by definition. That is not evidence of the trap.
    expect(() => {
      assertWeldDropped(3, 3, WELD_MIN_DROP, 1)
    }).not.toThrow()
    // A cube is the smallest closed thing the check runs on, and it clears it.
    expect(() => {
      assertWeldDropped(36, 8, WELD_MIN_DROP, 12)
    }).not.toThrow()
  })

  it('carries both counts in the error, so a failure is diagnosable', () => {
    const error = new WeldNoOpError(6_534_726, 6_488_791, 0.5)
    expect(error.ratio).toBeCloseTo(0.993, 3)
    expect(error.message).toContain('6488791')
    expect(error.message).toContain('facet normals')
  })
})

describe('the target band', () => {
  it('lands a mesh well above the ceiling inside the band', async () => {
    const stl = sphereStl(6)
    const parsed = parseStl(stl)
    expect(parsed.triangles).toBe(81_920)

    const result = await decimate(stl)
    expect(result.sourceTriangles).toBe(81_920)
    expect(result.passThrough).toBe(false)
    expect(result.triangles).toBeGreaterThanOrEqual(MIN_TRIANGLES * 0.98)
    expect(result.triangles).toBeLessThanOrEqual(MAX_TRIANGLES)
  })

  it('passes an already-small mesh through rather than inflating it', async () => {
    const result = await decimate(fixtureStl())
    expect(result.sourceTriangles).toBe(FIXTURE_TRIANGLES)
    expect(result.passThrough).toBe(true)
    expect(result.triangles).toBe(FIXTURE_TRIANGLES)
    expect(result.target).toBe(FIXTURE_TRIANGLES)
    // The floor is 5,000. Nothing here may reach for it.
    expect(result.triangles).toBeLessThan(MIN_TRIANGLES)
  })

  it('leaves a mesh exactly at the ceiling alone', async () => {
    const result = await decimate(sphereStl(5))
    expect(result.sourceTriangles).toBe(20_480)
    expect(result.passThrough).toBe(false)
    expect(result.triangles).toBeLessThanOrEqual(MAX_TRIANGLES)
  })

  it('honours an explicit band from the first target, not by retrying into it', async () => {
    const result = await decimate(sphereStl(6), { minTriangles: 1_000, maxTriangles: 2_000 })
    expect(result.triangles).toBeLessThanOrEqual(2_000)
    expect(result.target).toBeLessThanOrEqual(2_000)
    // One pass. Landing in a narrowed band by overshoot-retry would look the same
    // in `triangles` while having computed the first target against the wrong
    // ceiling, so the attempt count is the assertion that matters.
    expect(result.attempts).toBe(1)
  })

  it('escalates to the ceiling when the proportional target loses too much shape', async () => {
    // 5,120 triangles with a 50-triangle floor: 1% of the source is 52, and a
    // 52-triangle approximation of a 50 mm sphere is not a sphere.
    const result = await decimate(binaryStl(icosphere(4, 25)), { minTriangles: 50, maxTriangles: 4_000 })
    expect(result.target).toBe(4_000)
    expect(result.escalated).toBe(true)
    expect(result.attempts).toBe(2)
    expect(result.fidelity.acceptable).toBe(true)
  })

  it('does not escalate a mesh that was already faithful', async () => {
    const result = await decimate(sphereStl(6))
    expect(result.escalated).toBe(false)
    expect(result.attempts).toBe(1)
  })

  it('refuses a band it cannot reach, rather than shipping a heavy object', async () => {
    // 1,280 triangles cannot become 20 while remaining a closed surface, and the
    // retry budget is bounded.
    await expect(decimate(sphereStl(3), { minTriangles: 10, maxTriangles: 20 })).rejects.toThrow(
      TargetMissedError,
    )
  })

  it('reads both STL encodings', async () => {
    const soup = icosphere(4)
    const fromBinary = await decimate(binaryStl(soup))
    const fromAscii = await decimate(asciiStl(soup))
    expect(fromBinary.format).toBe('binary')
    expect(fromAscii.format).toBe('ascii')
    expect(fromAscii.sourceTriangles).toBe(fromBinary.sourceTriangles)
  })

  it('reports an unreachable target rather than shipping a heavy mesh', () => {
    const error = new TargetMissedError(41_000, MAX_TRIANGLES, 3)
    expect(error.message).toContain('41000')
    expect(error.message).toContain('20000')
  })
})

describe('the emitted GLB', () => {
  it('parses back with the triangle count the result claims', async () => {
    const result = await decimate(sphereStl(6))
    const summary = await readGlb(result.glb)
    expect(summary.triangles).toBe(result.triangles)
    expect(summary.vertices).toBe(result.vertices)
    // glTF Transform stamps `generator` itself on every write, so this tool's
    // own provenance rides in `extras` — see the constant's docblock.
    expect(summary.generator).toMatch(/^glTF-Transform /)
    expect(summary.tool).toBe(TOOL)
    expect(summary.copyright).toBe(COPYRIGHT)
    expect(summary.copyright).toContain('preview only')
  })

  it('carries POSITION and no NORMAL, so three flat-shades it', async () => {
    const result = await decimate(sphereStl(4))
    const summary = await readGlb(result.glb)
    expect(summary.hasNormals).toBe(false)
  })

  it('is meshopt-compressed and quantized by default, and says so', async () => {
    const result = await decimate(sphereStl(5))
    expect(result.compression).toBe('EXT_meshopt_compression')
    expect(result.extensionsRequired).toEqual(['EXT_meshopt_compression', 'KHR_mesh_quantization'])

    // The contract G2 must honour: quantization moves the scale onto the node.
    expect(result.node.scale[0]).toBeGreaterThan(1)
    const summary = await readGlb(result.glb)
    expect(summary.extensionsRequired).toContain('EXT_meshopt_compression')
    // Extents survive the round trip through the quantized accessor plus node scale.
    for (const axis of [0, 1, 2] as const) {
      expect(summary.extents[axis]).toBeCloseTo(result.source.extents[axis], 0)
    }
  })

  it('is bigger and transform-free without meshopt, which is the trade', async () => {
    const stl = sphereStl(5)
    const compressed = await decimate(stl)
    const plain = await decimate(stl, { meshopt: false })

    expect(plain.compression).toBe('none')
    expect(plain.extensionsRequired).toEqual([])
    expect(plain.node.translation).toEqual([0, 0, 0])
    expect(plain.node.scale).toEqual([1, 1, 1])
    expect(plain.glb.byteLength).toBeGreaterThan(compressed.glb.byteLength * 2)
  })

  it('is smaller than the STL — which is true with the trap armed, hence the weld check', async () => {
    const stl = sphereStl(6)
    const result = await decimate(stl)
    // Kept as a documented non-assertion: a GLB of the *same* geometry is smaller
    // than an STL regardless, so this comparison cannot detect the trap.
    expect(result.glb.byteLength).toBeLessThan(stl.byteLength)
  })

  it('reports a zero-facet STL instead of emitting an object', async () => {
    const empty = binaryStl(new Float32Array(0))
    expect(empty.byteLength).toBe(84)
    await expect(decimate(empty)).rejects.toThrow(EmptyMeshError)
  })

  it('handles a box, the smallest mesh the weld check applies to', async () => {
    const result = await decimate(binaryStl(box()))
    expect(result.sourceTriangles).toBe(12)
    expect(result.weld.before).toBe(36)
    expect(result.weld.after).toBe(8)
    expect(result.passThrough).toBe(true)
  })
})
