/**
 * The log a run resumes from, and the inventory the build reads.
 *
 * ## The log is the state
 *
 * Every finished blob — measured or failed — is appended as one JSON line before
 * the next dispatch, and a run reloads the log and skips what is in it. There is
 * no checkpoint file to fall out of sync with, nothing to clean up after a
 * `SIGINT`, and the key is the same md5 the inventory is keyed by. That is what
 * turns an interrupted 16 GB run into a resumed one rather than a repeated one.
 *
 * A failure is a line too, deliberately: a 404 or a mesh that hashes to
 * something else is a *finding* about the corpus, and re-attempting it on every
 * run would bury it. `--retry-failed` is how you ask for another go.
 *
 * ## The inventory is keyed by md5, and holds no half-measurements
 *
 * Only `measured` entries reach it. A host with no mounts still appears — its
 * `unresolved` list is the answer, and `classify.ts` gives a reason per slot —
 * but a blob whose bytes could not be trusted appears nowhere, so a consumer
 * that cannot find a blob has no mount data and must refuse rather than guess.
 * `counted.failed` is how many such blobs the log knows about, so the absence is
 * visible in the artefact rather than only in a terminal that has scrolled away.
 *
 * `MountInventory` is a plain interface here. Task 5 adds the Zod schema in
 * `pipeline/mounts.ts` and this type becomes the inferred one; the shape below is
 * what that schema is written against, member order included, because the
 * artefact is committed and a reordering would be a diff of the whole file.
 */
import { appendFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs'
import { dirname } from 'node:path'

import type { MountTarget, TargetKind } from './catalog'
import type { HostMeasurement, InsertMeasurement } from './classify'

/** The inventory's format version. Task 5's Zod schema pins the same number. */
export const MOUNT_INVENTORY_VERSION = 1

/** Names this tool in the artefact it writes, so a stale file is traceable. */
export const MOUNT_TOOL = 'openforge-workshop-mounts'

/** What the committed inventory says about itself. */
const NOTE =
  'Where accessories attach. Generated by `npm run mounts` from the meshes ' +
  'themselves; keyed by md5, because a re-export changes the mesh and must ' +
  'invalidate the measurement. Do not edit by hand.'

/** One blob that was read, parsed and measured. */
export interface MeasuredEntry {
  readonly blob: string
  readonly kind: TargetKind
  readonly status: 'measured'
  /** Object size in bytes, as the index states it. */
  readonly bytes: number
  readonly triangles: number
  /** Wall-clock seconds from request to measurement, for the run's own report. */
  readonly seconds: number
  /** Present for a host target. */
  readonly host?: HostMeasurement
  /** Present for an insert, and for a host that is also one. */
  readonly insert?: InsertMeasurement
}

/** One blob that was attempted and could not be trusted. */
export interface FailedEntry {
  readonly blob: string
  readonly kind: TargetKind
  readonly status: 'failed'
  readonly reason: string
}

export type LogEntry = MeasuredEntry | FailedEntry

/** How many of each thing the inventory holds. */
export interface MountCounts {
  readonly hosts: number
  readonly inserts: number
  readonly failed: number
  readonly mounts: number
}

/** The committed artefact. See the module docblock for the member order. */
export interface MountInventory {
  readonly note: string
  readonly version: typeof MOUNT_INVENTORY_VERSION
  /** ISO stamp of the run that produced it. */
  readonly measured: string
  /** The index it was measured against — `CatalogFile.version.fixtures`. */
  readonly catalog: { readonly fixtures: string }
  readonly tool: typeof MOUNT_TOOL
  readonly hosts: Record<string, HostMeasurement>
  readonly inserts: Record<string, InsertMeasurement>
  readonly counted: MountCounts
}

/* -------------------------------------------------------------------- the log */

/** Append one finished entry. Creates the directory and file on first use. */
export function appendEntry(logPath: string, entry: LogEntry): void {
  mkdirSync(dirname(logPath), { recursive: true })
  appendFileSync(logPath, `${JSON.stringify(entry)}\n`, 'utf8')
}

/**
 * Every entry the log holds, md5-keyed. A later line wins over an earlier one
 * for the same md5, so a retried failure is superseded by its success.
 *
 * A truncated final line — what an interrupted process leaves behind — is
 * dropped rather than throwing: the mesh gets re-read, which is the cheapest
 * correct response and costs one object.
 */
export function readLog(logPath: string): Map<string, LogEntry> {
  const entries = new Map<string, LogEntry>()
  if (!existsSync(logPath)) return entries
  for (const line of readFileSync(logPath, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (trimmed === '') continue
    let parsed: unknown
    try {
      parsed = JSON.parse(trimmed)
    } catch {
      continue
    }
    const entry = parsed as LogEntry
    if (typeof entry.blob !== 'string' || entry.blob === '') continue
    entries.set(entry.blob, entry)
  }
  return entries
}

/* -------------------------------------------------------------- the inventory */

/**
 * Assemble the inventory from log entries. Pure — no I/O.
 *
 * Keys are md5-sorted so two runs over the same corpus produce the same bytes
 * and the committed file diffs only where a measurement changed.
 */
export function buildInventory(
  entries: Iterable<LogEntry>,
  stamp: { readonly fixtures: string; readonly measured: string },
): MountInventory {
  const hosts: Record<string, HostMeasurement> = {}
  const inserts: Record<string, InsertMeasurement> = {}
  let failed = 0
  let mounts = 0

  for (const entry of [...entries].sort((a, b) => a.blob.localeCompare(b.blob))) {
    if (entry.status === 'failed') {
      failed += 1
      continue
    }
    if (entry.host !== undefined) {
      hosts[entry.blob] = entry.host
      mounts += entry.host.mounts.length
    }
    if (entry.insert !== undefined) inserts[entry.blob] = entry.insert
  }

  return {
    note: NOTE,
    version: MOUNT_INVENTORY_VERSION,
    measured: stamp.measured,
    catalog: { fixtures: stamp.fixtures },
    tool: MOUNT_TOOL,
    hosts,
    inserts,
    counted: { hosts: Object.keys(hosts).length, inserts: Object.keys(inserts).length, failed, mounts },
  }
}

/** The committed form: 2-space JSON, one trailing newline, git-diffable. */
export function serialise(inventory: MountInventory): string {
  return `${JSON.stringify(inventory, null, 2)}\n`
}

/* ---------------------------------------------------------------- sampling */

/**
 * Up to `n` targets, one per distinct shape of question before a second of any.
 *
 * A flat prefix of the work list is a poor sample: the manifest is ordinal-
 * ordered, which is roughly folder order, so the first fifty targets are fifty
 * variants of two designs. What `classify.ts` can get wrong varies with the slot
 * names it has to resolve, the footprint it frames the mesh by, and the family's
 * modelling conventions — so those three are the strata, and the sample covers
 * every combination that exists before it takes a second member of any of them.
 * Within a stratum, and for the fill, manifest order decides, so the sample is
 * deterministic and a re-run re-reads the same objects instead of new ones.
 */
export function stratifiedSample(targets: readonly MountTarget[], n: number): MountTarget[] {
  if (targets.length <= n) return [...targets]
  const buckets = new Map<string, MountTarget[]>()
  for (const target of [...targets].sort((a, b) => a.ord - b.ord)) {
    const key = `${target.slots.map((slot) => slot.name).join('+')}|${target.family}|${JSON.stringify(target.foot)}`
    const bucket = buckets.get(key)
    if (bucket === undefined) buckets.set(key, [target])
    else bucket.push(target)
  }

  const picks: MountTarget[] = []
  const spare: MountTarget[] = []
  for (const bucket of buckets.values()) {
    const [first, ...rest] = bucket
    if (first !== undefined) picks.push(first)
    spare.push(...rest)
  }
  spare.sort((a, b) => a.ord - b.ord)
  return [...picks, ...spare].slice(0, n)
}
