/**
 * Guided assemblies, as one import: `import { AssembliesScreen } from '@/screens/assemblies'`.
 *
 * Row C3 — **the 40 recipe templates as first-class objects**. Three things live
 * behind this barrel and the split is by kind:
 *
 *   - `templates.ts` — the 40, as generated data. **Generated by
 *     `pipeline/templates.ts`**, which reads the 20 `*.yaml` fixtures beside the
 *     JSON; `npm run import:catalog` writes it and `pipeline/templates.test.ts`
 *     asserts the committed bytes are the emitter's output. Not in
 *     `catalog.json`: none of the 40 carries `file_metadata`, so none is an STL
 *     and none is a `CatalogRecord` — and putting them in the index anyway was
 *     measured at +1,260 B brotli and declined, because the recipe list is the
 *     one part of this screen that renders before the index lands.
 *   - `assembly.ts` — pure and headless. Resolves a recipe's parts against a
 *     choice, works out which cards lead nowhere, and reports what each card
 *     would narrow.
 *   - `AssembliesScreen.tsx` — the control.
 *
 * Row C3's `fixtures.ts` — the strict reader and its round-trip proof — is gone
 * from here. Row X8 moved it to `pipeline/templates.ts`, which is the home C3
 * reported it belonged in, and nothing under `src/` reaches for the filesystem
 * any more; `tools/hygiene/project.test.ts` asserts that as a repository
 * property rather than as this directory's.
 *
 * ## What the row measured, and what it changed
 *
 * The row was written as *"with progressive narrowing"*, and row C2 had already
 * measured **0 narrowings in 33,221 sibling-effect observations** on tile
 * parents. Both hold, of different parents: over the templates the same method
 * gives **8,645 narrowings in 11,938 observations** — 72.4%, median 4.0× — and
 * the mechanism is that a template's own tags share **no root** with its
 * `constrain` entries, where a tile's share all of them. `assembly.ts` carries
 * the argument and `measure.ts` computes every figure in it.
 *
 * The user-facing size of that: walked cold, **39 of the 128 parts** would need
 * more than one page of cards. Walked in the recipe's declared order, so each
 * part is narrowed by the ones before it, **4 do**.
 *
 * ## What this row does not own
 *
 *   - **`@/composition`** is C1's — `constrain` semantics, the inverted index,
 *     the 0-byte argument. Imported, never modified. `resolveSlotTags` and
 *     `candidatesFor` are the whole interface this row needs, and it needs them
 *     precisely because a template is not a file: C2's picker takes a `TileId`
 *     parent and a template has no id in the manifest.
 *   - **C2's picker** is imported for two things and reimplemented for neither:
 *     `compositionIndexFor`, so the two screens share one inverted index, and
 *     `SlotFills`, for the accessory slots of a *chosen file*. One level, which
 *     is as deep as the archive goes.
 *   - **A1's private `slotKey`** is not needed. C2 flagged this row as the one
 *     most likely to want it; the parent here is a template, whose part names are
 *     unique within it (0 duplicates over 128), so `(template, part)` is total
 *     without it.
 *   - **The route.** `src/routes/**` is A4's, and this screen has no `path`
 *     entry yet. `AssembliesScreen.tsx` names the exact declaration; it is one
 *     `createRoute` and one array member, with no search params.
 */
export type {
  AssemblyChoice,
  AssemblyOption,
  AssemblyState,
  AssemblyStep,
  RecipeIndex,
  RecipeTemplate,
  StepNarrowing,
  TemplatePart,
} from './assembly'
export {
  STEP_PAGE,
  assemblyState,
  assemblyStepKey,
  createRecipeIndex,
  deadEndSentence,
  emptyStepSentence,
  narrowingSentence,
  resolvePart,
  stepCountSentence,
} from './assembly'

/*
 * The generated data, all three exports.
 *
 * `RECIPE_TEMPLATES` is the 40 read from the fixtures; row **B4** added the 51
 * generated families and their size table beside it and owed this line.
 * `GENERATED_FAMILIES` is a **second export** rather than 51 more entries in the
 * first, because that array's length is asserted to be 40 in six suites and
 * quoted on this screen as *"N recipes from the archive's own blueprint
 * fixtures"* — which the families are not.
 *
 * Row C1's palette reads all three through `builder/panels/families.ts`, which
 * imports `./templates` directly rather than this barrel: a value import of this
 * module reaches `AssembliesScreen.tsx` and its stylesheet, and the palette
 * needs two arrays and a table.
 */
export { GENERATED_FAMILIES, GENERATED_FAMILY_SIZES, RECIPE_TEMPLATES } from './templates'

export { AssembliesScreen } from './AssembliesScreen'
